services:
  - type: web
    name: neuro-silicon-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_ID
        value: KrishnaGana@12
      - key: ADMIN_PASS
        value: Muddukrishna@12
